[project]
name = "streamlitapp"
version = "0.1.0"
description = ""
authors = [
    {name = "paulocardoso"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.0.0",
    "requests>=2.26.0",
    "pandas>=1.3.0"
]
